### ISSUE TITLE
Enclosure as a teachable experience

### ISSUE THREAD

**Issue by frankcohen** [softegg/supercon-2023-badge-enclosure#1]
Hi @softegg thanks for the case, I'm going to print it on a Elegoo Saturn resin printer in a clear resin. I'm working on my Reflections open-source wrist watch project https://github.com/frankcohen/ReflectionsOS. I've been wondering how I can make press-able buttons on the watch case that would activate SMT buttons on its main board. I'm hoping your badge enclosure will teach me about buttons.

One thing that concerns me about your enclosure... so many objects to print! Wow.

Thank you.

-Frank

**Comment by softegg** [comment]
The best teacher is always to take apart some things that work the way you want your project to work and see what they did.

For buttons, the main things are that they don't bind and they don't fall in the case. If you have labels on them, maybe make sure they don't spin also. 
Having a draft angle that makes them smaller near the top helps keep them in the case, but it is good to have some sort of a lip also. I used the spin prevention nubs for that, but that kinda means you can see LEDs blinking in the case around the buttons, so maybe I coulda done better with a full lip.
The design very much depends on what they are actually pushing, whether they can attach to that, if they need to come off for cleaning, how deep you enclosure is, etc.

You prototype until you have something that works, and try to produce it with a process that gets you as close to your finished process as possible.

In injection molding, you need draft angle to you can get the parts out of the mold, and vents so that the air has a way to escape when they plastic comes in. If it's deep, you might need a pusher to push the part out of the mold. And you need an easy parting line where the mold separate and the draft angle reverses. Oh, and an injection point for the plastic to go in.
Any hole or edge leaves a scar or sprue, so you want this in areas that you can't see, and that won't cause a mechanical failure to the motion of the button.
Resin casting is similar, but more forgiving because the silicon molds bend, but then you have to worry about part warping too, on larger parts. Also, mold release is really important so as not to tear the mold.

If you are 3d printing, you have different concerns. Resin is mainly about where your supports go, how resin drains, and build plate adhesion. 
FDM has support, infill, grain, bed adhesion, resolution and a while host of other issues.

So you design your posts with your manufacturing process, both prototyping and manufacturing, in mind, as well as the mechanical function, and aesthetics.

It's fun, but there are always revisions and tweaks before you get it right. I'm amazed that the first draft enclosure came out as good as it did, TBH. But even that had buttons that bind...

Anyway, good luck. I'm available for hire if you don't want to do it yourself...

**Comment by frankcohen** [comment]
Thanks for the advice, I appreciate you writing your advice to me.

I'm a software guy who is learning by doing a combination hardware/software project. Reflections first instance is a wrist watch. There are two surface mounted switches on the main board. They have push button pins on their sides. I need 2 easy buttons to be at the watch case and reach in to press the buttons on the main board.

My plan is to prototype the watch case using clear resin (printed on an Elegoo Saturn printer), then take the final prototypes to a manufacturer. The manufacturer builds the case design to be milled from stainless steel. I would be fine if you tell me not to do this process?

Not so great progress on printing the Supercon board protector today. Trying again tomorrow.

![IMG20231031220333](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/b21233f3-2c47-4f71-8b59-b67e32609a87)
![IMG20231031220419](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/9c2d1dd5-8f36-4680-b980-965d2edfce08)
![IMG20231031220322](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/832d2396-3849-4a8a-8bfe-dad66920b9b1)

-Frank
