### ISSUE TITLE
Printing All At Once

### ISSUE THREAD

**Issue by frankcohen** [softegg/supercon-2023-badge-enclosure#2]
My first print experiences for the enclosure didn't go so well. :-D
![screenshot_8375](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/3c9a72bc-ff8c-4675-ab1d-a598b07ab6d4)

I rotated the case to keep it from adhering to the build plate. Instead, that's just what it did. :-o

My attempt today is to print all the components all at once. It's my homage to Jobu Tupaki, "I got bored one day and put everything on a bagel." Although perhaps this strategy will be more like Evelyn saying 'We are all small and stupid."

![screenshot_8374](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/0c2a5baf-4dad-4387-88b2-d684e5e512f9)

6 1/2 hours, 1,792 layers, and a full tank of water-washable clear resin... what could go wrong?

Please wish me luck!

See you all tomorrow!

-Frank

**Comment by softegg** [comment]
Resin printing can be tricky. The first ones you did seem like they were perhaps not exposed long enough, and then not UV cured after the bath in IPA alcohol, maybe? I'm not an expert, either.
Have you done resin prints before? Have these settings worked on other projects?
What I do know is that you have to be very careful to try not to print large areas unless they are attached to a large amount of support from previous layers or from added supports. Otherwise it glues itself to the FEP film and you don't end up with a print, you end up with a big flat blob.
But that doesn't seem to be your problem.

Obviously, the model doesn't really have anything to do with it, so I can only suggest that your machine is probably not set up correctly for the resin that you are using. Also, make sure to get the bubbles out of the resin before you start printing. You never shake up resin, you kinda slosh it for a few minutes, trying not to get air bubbles in it, before pouring it into the tray. I usually rake it a few times with the plastic spatula (being careful not to scrape the FEP film!)  to make sure it is mixed and to move remaining bubbles out of the build area.

Anyway, sorry if I am over-explaining stuff you already know!

Good luck with your prints!

**Comment by frankcohen** [comment]
Not overexplaining, cause I'm not the only one printing tonight! :-D

I've been printing on this Elegoo Saturn S for about 6 months and it works great.

You did a fine job at building the model. The print set-up includes how to support the model, how to avoid FEP bunching, printing large areas, as you say. The model could have been broken down into smaller interlocking pieces to make printing easier.

It's printing over night tonight. You'll ether see me with a kickass crystal board protector, or not. Either way it's been a good learning experience! Thanks!

-Frank

**Comment by frankcohen** [comment]
Better...
![IMG20231102000307](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/56e51d09-a49b-401c-9808-ee91cc8db548)
![IMG20231102000312](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/61744ab4-ae5f-463a-8cd3-2d97573091ea)
![IMG20231102000322](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/3b91c23a-9c40-470d-82d9-697b352726c8)

**Comment by frankcohen** [comment]
One more try before I get onto the flight tomorrow

**Comment by frankcohen** [comment]
Success! See you all tomorrow. -Frank
![IMG20231102075945](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/83ea24db-5e24-4c6f-a8dd-6252200f6402)
![IMG20231102075952](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/a8dd5620-8c05-48a6-b67f-dea66b2611e5)
![IMG20231102080000](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/aec79631-4af4-4091-ac62-b521b4162a8a)
![Uploading IMG20231102080038.jpg…]()

**Comment by frankcohen** [comment]
sorry, here are the correct photos.
![IMG20231102075945](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/aae64ca3-74d9-49de-9bd9-50ab543e433b)
![IMG20231102075952](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/b586531e-7a00-498c-b962-6daf9bacfcf5)
![IMG20231102080000](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/3dd4c945-8507-45ad-9d3f-ab4dfe98bbe6)
![IMG20231102080038](https://github.com/softegg/supercon-2023-badge-enclosure/assets/6834993/df3d2e16-6a93-4fab-9154-996ec35780f2)

**Comment by softegg** [comment]
Glad it all worked out!
